### ISSUE TITLE
error in run test.py

### ISSUE THREAD

**Issue by kekezhang112** [TH3CHARLie/deep-high-dynamic-range#2]
Hi,
I am studying your code, but an error occurs and I can not solve it even trying many solutions from the internet.
First, I run the 'preprocess.py' to generate the data. Then, I run 'python test.py direct saved-checkpoints/deepflow-direct/model.ckpt-100' in terminal. But an error occurs:
' W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at iterator_ops.cc:929 : Unknown: NewRandomAccessFile failed to Create/Open: ./tf-data/test-deepflow/SceneEXTRA : 拒绝访问。
; Input/output error
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    test_model()
  File "test.py", line 49, in test_model
    for (inputs, label) in test_dataset:
  File "C:\Users\zkk\Anaconda3\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "C:\Users\zkk\Anaconda3\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\Users\zkk\Anaconda3\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\zkk\Anaconda3\envs\py37\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2677, in iterator_get_next_sync
    "output_types", output_types, "output_shapes", output_shapes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 80: invalid start byte
'
Could you please help me?
Thank you very much!

**Comment by TH3CHARLie** [comment]
Which version of TensorFlow are you using? I am guessing this is caused by a mismatch of the TF version. This repo is completely using TensorFlow==2.0

**Comment by kekezhang112** [comment]
The version of Tensorflow is 2.0. Windows, CUDA10. The error still exists.

**Comment by TH3CHARLie** [comment]
I haven't tested this on Windows and I do not own a windows machine. But your error log says "./tf-data/test-deepflow/SceneEXTRA : 拒绝访问。". Does this mean your terminal has no access to the data folder?

**Comment by kekezhang112** [comment]
I open the terminal in 'run as administrator'(以管理员身份运行). I think the error occurs in 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 80: invalid start byte'. Unfortunatelly, I can not solve it...

**Comment by kekezhang112** [comment]
Hi,
The error is solved by change the 'config.py'   TEST_DATA_PATH = "./tf-data/test-deepflow/" to TEST_DATA_PATH = "./tf-data/test-deepflow/ScenePAPER" and TEST_DATA_PATH = "./tf-data/test-deepflow/SceneEXTRA"    respectively.
Windows 10, tensorflow 2.0, CUDA10.
Thanks.
