### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by starlitCoding** [TH3CHARLie/deep-high-dynamic-range#3]
大佬，我最近在看这个论文，直接下载你的代码跑了一下，结果前边修修补补都跑过来了结果到train.py这个文件报的一个错实在是找不到原因了，该创建的文件夹 都已经创建好了（OP_REQUIRES failed at iterator_ops.cc:941 : Unknown: NewRandomAccessFile failed to Create/Open: ./tf-data/test-deepflow/SceneEXTRA : �ܾ����ʡ�）

**Comment by TH3CHARLie** [comment]
https://github.com/TH3CHARLie/deep-high-dynamic-range/issues/2 这个你看看对你有帮助吗？除此之外，这个有可能是编码导致的？
